
jobs:
  include:
    - stage: build-image
      script:
        - echo $TRAVIS_BUILD_NUMBER > version.txt
        - docker build --build-arg VCS_REF=`git rev-parse --short HEAD` -t lineops/nginx-webdav .

      after_success:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker tag lineops/nginx-webdav lineops/nginx-webdav:$TRAVIS_BUILD_NUMBER
        - docker push lineops/nginx-webdav:$TRAVIS_BUILD_NUMBER
        - docker push lineops/nginx-webdav:latest
        - curl -XPOST https://hooks.microbadger.com/images/gbnk0/nginx-webdav/_WZPSkqhhy137pspxCtRGxofefI=
branches:
  only:
    - master